#!/usr/bin/env python3
"""Flatten the shared article imports in their original cascade order.

Edit the leaf styles or articles-entry.css, then rebuild. --check prevents
shipping a stale bundle. Paths stay absolute and no CSS rules are rewritten.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENTRY = ROOT / "assets/articles-entry.css"
OUTPUT = ROOT / "assets/articles.css"
IMPORT = re.compile(r'@import url\("(/assets/[^"\n]+\.css)"\);')


def bundle() -> str:
    def replace(match: re.Match) -> str:
        path = ROOT / match[1].lstrip("/")
        source = path.read_text()
        if "@import" in source or "@charset" in source:
            raise ValueError(f"Review nested import/charset before bundling {path}")
        for url in re.findall(r'url\([\"\']?([^\)\"\']+)', source):
            if not url.startswith(("/", "data:", "https:", "http:", "#")):
                raise ValueError(f"Relative URL needs rebasing: {path}: {url}")
        return f"/* Source: {match[1]} */\n{source}"

    content = IMPORT.sub(replace, ENTRY.read_text())
    if "@import" in content:
        raise ValueError("Unsupported import in entry")
    return "/* Generated by tools/build_article_styles.py; edit source styles. */\n" + content


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = bundle()
    if args.check:
        if OUTPUT.read_text() != content:
            raise SystemExit("Shared CSS bundle is stale; run tools/build_article_styles.py")
        print("Shared CSS bundle matches its sources; no nested stylesheet requests")
    else:
        OUTPUT.write_text(content)
        print(f"Built {OUTPUT.relative_to(ROOT)}: {len(content.encode())} bytes, five nested requests removed")
